# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'diseñodFUYeI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)
from imagenes import *

class Ui_Poke_Api(object):
    def setupUi(self, Poke_Api):
        if not Poke_Api.objectName():
            Poke_Api.setObjectName(u"Poke_Api")
        Poke_Api.setWindowModality(Qt.WindowModal)
        Poke_Api.resize(650, 677)
        icon = QIcon()
        icon.addFile(u":/imagenes/pokebola.png", QSize(), QIcon.Normal, QIcon.Off)
        Poke_Api.setWindowIcon(icon)
        self.centralwidget = QWidget(Poke_Api)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 0, 131, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(230, 40, 181, 21))
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(280, 70, 75, 24))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setBold(True)
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.seleccionar = QComboBox(self.centralwidget)
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.addItem("")
        self.seleccionar.setObjectName(u"seleccionar")
        self.seleccionar.setGeometry(QRect(250, 440, 191, 31))
        self.seleccionar.setFont(font1)
        self.seleccionar.setFocusPolicy(Qt.NoFocus)
        self.seleccionar.setStyleSheet(u"background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 20, 121, 51))
        self.label_3.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.label_3.setPixmap(QPixmap(u":/imagenes/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 330, 81, 31))
        font2 = QFont()
        font2.setFamilies([u"Arial Black"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 380, 41, 31))
        self.label_5.setFont(font2)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(270, 330, 61, 31))
        self.label_6.setFont(font2)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(270, 380, 51, 31))
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(440, 330, 51, 31))
        self.label_8.setFont(font2)
        self.listado = QTextEdit(self.centralwidget)
        self.listado.setObjectName(u"listado")
        self.listado.setGeometry(QRect(20, 480, 611, 171))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 0, 651, 111))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"background-color: rgb(61, 61, 61);")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(220, 130, 191, 171))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"background-color: rgb(61, 61, 61);")
        self.imagen = QLabel(self.centralwidget)
        self.imagen.setObjectName(u"imagen")
        self.imagen.setGeometry(QRect(230, 140, 171, 151))
        self.imagen.setFont(font3)
        self.imagen.setStyleSheet(u"background-color: rgb(61, 61, 61);\n"
"background-color: rgb(148, 148, 148);")
        self.lnombre = QLabel(self.centralwidget)
        self.lnombre.setObjectName(u"lnombre")
        self.lnombre.setGeometry(QRect(120, 330, 131, 31))
        self.lnombre.setFont(font3)
        self.lnombre.setFrameShape(QFrame.NoFrame)
        self.lid = QLabel(self.centralwidget)
        self.lid.setObjectName(u"lid")
        self.lid.setGeometry(QRect(120, 380, 71, 31))
        self.lid.setFont(font3)
        self.lid.setFrameShape(QFrame.NoFrame)
        self.laltura = QLabel(self.centralwidget)
        self.laltura.setObjectName(u"laltura")
        self.laltura.setGeometry(QRect(340, 330, 81, 31))
        self.laltura.setFont(font3)
        self.laltura.setFrameShape(QFrame.NoFrame)
        self.lpeso = QLabel(self.centralwidget)
        self.lpeso.setObjectName(u"lpeso")
        self.lpeso.setGeometry(QRect(340, 380, 71, 31))
        self.lpeso.setFont(font3)
        self.lpeso.setFrameShape(QFrame.NoFrame)
        self.ltipo = QLabel(self.centralwidget)
        self.ltipo.setObjectName(u"ltipo")
        self.ltipo.setGeometry(QRect(490, 330, 131, 31))
        self.ltipo.setFont(font3)
        self.ltipo.setFrameShape(QFrame.NoFrame)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 440, 221, 31))
        self.label_11.setFont(font2)
        Poke_Api.setCentralWidget(self.centralwidget)
        self.label_10.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.seleccionar.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.listado.raise_()
        self.imagen.raise_()
        self.lnombre.raise_()
        self.lid.raise_()
        self.laltura.raise_()
        self.lpeso.raise_()
        self.ltipo.raise_()
        self.label_11.raise_()
        self.statusbar = QStatusBar(Poke_Api)
        self.statusbar.setObjectName(u"statusbar")
        Poke_Api.setStatusBar(self.statusbar)

        self.retranslateUi(Poke_Api)

        QMetaObject.connectSlotsByName(Poke_Api)
    # setupUi

    def retranslateUi(self, Poke_Api):
        Poke_Api.setWindowTitle(QCoreApplication.translate("Poke_Api", u"Poke Api", None))
        self.label.setText(QCoreApplication.translate("Poke_Api", u"Buscar Pokemon", None))
        self.pushButton.setText(QCoreApplication.translate("Poke_Api", u"Buscar", None))
        self.seleccionar.setItemText(0, QCoreApplication.translate("Poke_Api", u"Generacion 1", None))
        self.seleccionar.setItemText(1, QCoreApplication.translate("Poke_Api", u"Generacion 2", None))
        self.seleccionar.setItemText(2, QCoreApplication.translate("Poke_Api", u"Generacion 3", None))
        self.seleccionar.setItemText(3, QCoreApplication.translate("Poke_Api", u"Generacion 4", None))
        self.seleccionar.setItemText(4, QCoreApplication.translate("Poke_Api", u"Generacion 5", None))
        self.seleccionar.setItemText(5, QCoreApplication.translate("Poke_Api", u"Generacion 6", None))
        self.seleccionar.setItemText(6, QCoreApplication.translate("Poke_Api", u"Generacion 7", None))
        self.seleccionar.setItemText(7, QCoreApplication.translate("Poke_Api", u"Generacion 8", None))
        self.seleccionar.setItemText(8, QCoreApplication.translate("Poke_Api", u"Generacion 9", None))

        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("Poke_Api", u"Nombre:", None))
        self.label_5.setText(QCoreApplication.translate("Poke_Api", u"ID:", None))
        self.label_6.setText(QCoreApplication.translate("Poke_Api", u"Altura: ", None))
        self.label_7.setText(QCoreApplication.translate("Poke_Api", u"Peso:", None))
        self.label_8.setText(QCoreApplication.translate("Poke_Api", u"Tipo:", None))
        self.label_9.setText("")
        self.label_10.setText("")
        self.imagen.setText("")
        self.lnombre.setText("")
        self.lid.setText("")
        self.laltura.setText("")
        self.lpeso.setText("")
        self.ltipo.setText("")
        self.label_11.setText(QCoreApplication.translate("Poke_Api", u"Seleccionar Generaci\u00f3n", None))
    # retranslateUi

